name: "Pseudotrue news"
description: "Updates from Gray Calhoun's homepage"
permalink: /notes/:title
markdown: rdiscount
exclude: ['*~',
          '*.aux',
          '*.bbl',
          '*.blg',
          '*.dvi',
          '*.fdb_latexmk',
          '*.fls',
          '*.log',
          '*.out',
          '671/*.bib',
          '674/*.bib',
          'CNAME',
          'econupload.sh']
url: ''
main: 'http://pseudotrue.com'